fortunes/config/routes.rb
Fortunes::Application.routes.draw do
  resources :fortunes

end

fortunes/app/models/fortune.rb
class Fortune < ActiveRecord::Base
  attr_accessible :text
end

fortunes/app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  # GET /fortunes
  # GET /fortunes.json
  def index
    @fortunes = Fortune.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fortunes }
    end
  end

  # GET /fortunes/1
  # GET /fortunes/1.json
  def show
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/new
  # GET /fortunes/new.json
  def new
    @fortune = Fortune.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/1/edit
  def edit
    @fortune = Fortune.find(params[:id])
  end

  # POST /fortunes
  # POST /fortunes.json
  def create
    @fortune = Fortune.new(params[:fortune])

    respond_to do |format|
      if @fortune.save
        format.html { redirect_to @fortune, notice: 'Fortune was successfully created.' }
        format.json { render json: @fortune, status: :created, location: @fortune }
      else
        format.html { render action: "new" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fortunes/1
  # PUT /fortunes/1.json
  def update
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      if @fortune.update_attributes(params[:fortune])
        format.html { redirect_to @fortune, notice: 'Fortune was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fortunes/1
  # DELETE /fortunes/1.json
  def destroy
    @fortune = Fortune.find(params[:id])
    @fortune.destroy

    respond_to do |format|
      format.html { redirect_to fortunes_url }
      format.json { head :no_content }
    end
  end
end

fortunes/app/helpers/fortunes_helper.rb
module FortunesHelper
end

fortunes/app/views/fortunes/_form.html.erb
<%= form_for(@fortune) do |f| %>
  <% if @fortune.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fortune.errors.count, "error") %> prohibited this fortune from being saved:</h2>

      <ul>
      <% @fortune.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

fortunes/app/views/fortunes/edit.html.erb
<h1>Editing fortune</h1>

<%= render 'form' %>

<%= link_to 'Show', @fortune %> |
<%= link_to 'Back', fortunes_path %>

fortunes/app/views/fortunes/index.html.erb
<h1>Listing fortunes</h1>

<table>
  <tr>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fortunes.each do |fortune| %>
  <tr>
    <td><%= fortune.text %></td>
    <td><%= link_to 'Show', fortune %></td>
    <td><%= link_to 'Edit', edit_fortune_path(fortune) %></td>
    <td><%= link_to 'Destroy', fortune, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fortune', new_fortune_path %>

fortunes/app/views/fortunes/new.html.erb
<h1>New fortune</h1>

<%= render 'form' %>

<%= link_to 'Back', fortunes_path %>

fortunes/app/views/fortunes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @fortune.text %>
</p>


<%= link_to 'Edit', edit_fortune_path(@fortune) %> |
<%= link_to 'Back', fortunes_path %>

fortunes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fortunes</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>